favicons:
  "16": https://bucket-wei.webdong.dev/favicon/favicon-16x16.png
  "32": https://bucket-wei.webdong.dev/favicon/favicon-32x32.png
  "512": https://bucket-wei.webdong.dev/favicon/favicon-512x512.png
  android-chrome-192: https://bucket-wei.webdong.dev/favicon/android-chrome-192x192.png
  android-chrome-512: https://bucket-wei.webdong.dev/favicon/android-chrome-512x512.png
  apple-touch-icon: https://bucket-wei.webdong.dev/favicon/apple-touch-icon.png
globalOgImage:
  url: https://bucket-wei.webdong.dev/global/og-image.jpg
  height: 630
  width: 1200
  type: image/jpeg
website:
  name: Letter
  username: Joe
  email: bottle200918@gmail.com
  emojiStatus: 🍙
  globalBackgroundTextureImage: https://bucket-wei.webdong.dev/global/natural-paper.webp
  globalHighlightTextureImage: https://bucket-wei.webdong.dev/global/highlight-texture.webp
  socials:
    - name: Blog
      url: https://www.webdong.dev/
    - name: GitHub
      url: https://github.com/riceball-tw
    - name: Threads
      url: https://www.threads.net/@webdong.dev
    - name: Behance
      url: https://www.behance.net/riceballwei
    - name: CakeResume
      url: https://www.cakeresume.com/me/Riceball-wei
heroVideo:
  poster: https://bucket-wei.webdong.dev/hero-blur.webp
  sources:
    - src: https://bucket-wei.webdong.dev/hero.webm
      type: video/webm
    - src: https://bucket-wei.webdong.dev/hero.mp4
      type: video/mp4
techGroups:
  - id: "Work-TechGroup-all"
    relatedTechs: []
    icon: "material-symbols:person-play-outline-rounded"
    themeColor: "#171717"
  - id: "Work-TechGroup-UserInterface"
    relatedTechs:
      - "Bootstrap"
      - "Chart.js"
      - "Daisy UI"
      - "Framer Motion"
      - "GSAP"
      - "Shadcn UI"
    icon: "material-symbols:layers-outline-rounded"
    themeColor: "#5c038f"
  - id: "Work-TechGroup-Vue"
    relatedTechs:
      - "Nuxt(Vue)"
      - "Pinia"
      - "Vue"
      - "Vue Router"
    icon: "mdi:vuejs"
    themeColor: "#33a06f"
  - id: "Work-TechGroup-React"
    relatedTechs:
      - "Next(React)"
      - "React"
      - "React Router"
    icon: "mdi:react"
    themeColor: "#087ea4"
  - id: "Work-TechGroup-Testing"
    relatedTechs:
      - "Playwright"
      - "Vitest"
      - "Cypress"
      - "Lighthouse CI"
      - "Node.js Test Runner"
      - "Go Test"
    icon: "material-symbols:thermostat-rounded"
    themeColor: "#608f03"
  - id: "Work-TechGroup-Database"
    relatedTechs:
      - "Supabase(Postgres)"
      - "MySQL"
      - "Drizzle ORM"
    icon: "material-symbols:database-outline"
    themeColor: "#03118f"
